create extension if not exists pgcrypto with schema extensions;

create table if not exists public.usuarios (
  id uuid not null default gen_random_uuid(),
  nombre varchar not null,
  apellido varchar not null,
  email varchar not null unique,
  username varchar not null unique,
  password_hash varchar not null,
  rol varchar default 'free' check (rol in ('free', 'premium', 'admin')),
  es_premium boolean default false,
  premium_hasta timestamptz,
  premium_cancelado boolean default false,
  puntos integer default 0,
  bio text default '',
  foto_perfil text,
  preferencias jsonb default '[]'::jsonb,
  fecha_registro timestamptz default now(),
  ultimo_acceso timestamptz,
  constraint usuarios_pkey primary key (id)
);

create table if not exists public.recetas (
  id integer generated by default as identity,
  titulo varchar not null,
  descripcion text default '',
  ingredientes text not null,
  pasos text not null,
  precio varchar default '$$',
  precio_numerico numeric default 0,
  tiempo varchar default '30 min',
  tiempo_numerico integer default 30,
  imagen text,
  video_url text,
  video_youtube text,
  es_premium boolean default false,
  etiquetas jsonb default '[]'::jsonb,
  autor varchar,
  usuario_id uuid,
  likes integer default 0,
  comentarios_count integer default 0,
  fecha timestamptz default now(),
  updated_at timestamptz default now(),
  porciones text default '2-4',
  constraint recetas_pkey primary key (id),
  constraint recetas_usuario_id_fkey foreign key (usuario_id) references public.usuarios(id)
);

create table if not exists public.comentarios (
  id integer generated by default as identity,
  receta_id integer,
  usuario_id uuid,
  texto text not null,
  contenido text,
  autor varchar,
  padre_id integer,
  fecha timestamptz default now(),
  constraint comentarios_pkey primary key (id),
  constraint comentarios_receta_id_fkey foreign key (receta_id) references public.recetas(id),
  constraint comentarios_usuario_id_fkey foreign key (usuario_id) references public.usuarios(id),
  constraint comentarios_padre_id_fkey foreign key (padre_id) references public.comentarios(id)
);

create table if not exists public.favoritos (
  id integer generated by default as identity,
  receta_id integer,
  usuario_id uuid,
  fecha timestamptz default now(),
  constraint favoritos_pkey primary key (id),
  constraint favoritos_receta_id_fkey foreign key (receta_id) references public.recetas(id),
  constraint favoritos_usuario_id_fkey foreign key (usuario_id) references public.usuarios(id)
);

create table if not exists public.historial (
  id integer generated by default as identity,
  usuario_id uuid,
  receta_id integer,
  fecha timestamptz default now(),
  constraint historial_pkey primary key (id),
  constraint historial_usuario_receta_key unique (usuario_id, receta_id),
  constraint historial_usuario_id_fkey foreign key (usuario_id) references public.usuarios(id),
  constraint historial_receta_id_fkey foreign key (receta_id) references public.recetas(id)
);

create table if not exists public.likes (
  id integer generated by default as identity,
  receta_id integer,
  usuario_id uuid,
  fecha timestamptz default now(),
  constraint likes_pkey primary key (id),
  constraint likes_receta_id_fkey foreign key (receta_id) references public.recetas(id),
  constraint likes_usuario_id_fkey foreign key (usuario_id) references public.usuarios(id)
);

create table if not exists public.lista_compras (
  id integer generated by default as identity,
  usuario_id uuid unique,
  items jsonb default '[]'::jsonb,
  updated_at timestamptz default now(),
  constraint lista_compras_pkey primary key (id),
  constraint lista_compras_usuario_id_fkey foreign key (usuario_id) references public.usuarios(id)
);

create table if not exists public.metodos_pago (
  id integer generated by default as identity,
  usuario_id uuid,
  tarjeta_mask varchar not null,
  token_pago varchar not null,
  fecha_registro timestamptz default now(),
  constraint metodos_pago_pkey primary key (id),
  constraint metodos_pago_usuario_id_fkey foreign key (usuario_id) references public.usuarios(id)
);

create table if not exists public.notificaciones (
  id integer generated by default as identity,
  usuario_id uuid,
  tipo varchar,
  leida boolean default false,
  mensaje text not null,
  metadata jsonb,
  created_at timestamptz default now(),
  constraint notificaciones_pkey primary key (id),
  constraint notificaciones_usuario_id_fkey foreign key (usuario_id) references public.usuarios(id)
);

create table if not exists public.otp_tokens (
  id integer generated by default as identity,
  email varchar not null,
  otp varchar not null,
  tipo varchar default 'registro',
  datos jsonb,
  usado boolean default false,
  expires_at timestamptz not null,
  created_at timestamptz default now(),
  constraint otp_tokens_pkey primary key (id)
);

create table if not exists public.planes_semanales (
  id integer generated by default as identity,
  usuario_id uuid unique,
  plan jsonb not null default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint planes_semanales_pkey primary key (id),
  constraint planes_semanales_usuario_id_fkey foreign key (usuario_id) references public.usuarios(id)
);

create table if not exists public.precios_ingredientes (
  id integer generated by default as identity,
  nombre text not null unique,
  precio_por_unidad numeric not null,
  unidad text default 'pieza',
  ultima_actualizacion timestamptz default now(),
  constraint precios_ingredientes_pkey primary key (id)
);

create table if not exists public.puntos_log (
  id integer generated by default as identity,
  usuario_id uuid,
  accion varchar not null,
  puntos integer not null,
  descripcion text,
  fecha timestamptz default now(),
  constraint puntos_log_pkey primary key (id),
  constraint puntos_log_usuario_id_fkey foreign key (usuario_id) references public.usuarios(id)
);

create table if not exists public.push_subscriptions (
  id integer generated by default as identity,
  user_id uuid,
  subscription jsonb not null,
  created_at timestamptz default now(),
  constraint push_subscriptions_pkey primary key (id),
  constraint push_subscriptions_user_id_fkey foreign key (user_id) references public.usuarios(id)
);
